### ISSUE TITLE
在Check a kernel output files报错

### ISSUE THREAD

**Issue by Wcoom** [xiaoleGun/KernelSU_Action#100]
Run cd $GITHUB_WORKSPACE/kernel_workspace
Kernel output file is empty
Error: Process completed with exit code 1.
作者大大，这是设置错误？

**Comment by Wcoom** [comment]
![Uploading Screenshot_2023-10-08-21-45-58-079_com.android.chrome-edit.jpg…]()

**Comment by Wcoom** [comment]
![Uploading Screenshot_2023-10-08-22-10-11-435_com.android.chrome-edit.jpg…]()

**Comment by xiaoleGun** [comment]
设置错误
