### ISSUE TITLE
使用ksud debug get-sign <apk_path>

### ISSUE THREAD

**Issue by bgaojin** [xiaoleGun/KernelSU_Action#114]
很抱歉 我是c语音的初学者，不知道怎么使用这个命令 。hash通过keytools 获取了，这个size是如何理解 就是key.jks的文件大小吗 然后转成16进制吗

**Comment by xiaoleGun** [comment]
直接找ksud这个二进制可执行文件，在包含它的目录内打开终端，然后chmod -x ksud，输入命令 <apk_path>是你自编译kernelsu管理器的绝对或相对路径
