### ISSUE TITLE
请问boot.img是什么手机什么版本的内核

### ISSUE THREAD

**Issue by thofd** [xiaoleGun/KernelSU_Action#117]
首先感谢项目主的贡献，请问boot.img是什么手机什么版本的内核

**Comment by xiaoleGun** [comment]
同系统同内核源码编译出来的，普通用户一般不需要

**Comment by thofd** [comment]
感谢项目主弄的这么好一个在线编译的脚本，我去尝试一下我的手机redmi note9 pro,生成一个可用的KSU先，感谢说明！
