### ISSUE TITLE
为什么一直卡在这啊，config.env里的kernelSU_Tag设置main、具体版号（v0.7.6）、或者空值都试过，都会卡在Setup KernelSU这步。

### ISSUE THREAD

**Issue by univers629** [xiaoleGun/KernelSU_Action#123]
![image](https://github.com/xiaoleGun/KernelSU_Action/assets/111641284/5d44e686-3cff-4ec6-9d00-fe56c4232197)

**Comment by univers629** [comment]
可以直接访问我的仓库看看配置https://github.com/univers629/K40G_KernelSU_Action/blob/main/config.env

**Comment by bdqllW** [comment]
试试这个
https://github.com/bdqllW/KernelSU_Action/commit/f6a357b1f40c1250fb16aa6507982a193b97c2b4

**Comment by univers629** [comment]
> 试试这个 [bdqllW@f6a357b](https://github.com/bdqllW/KernelSU_Action/commit/f6a357b1f40c1250fb16aa6507982a193b97c2b4)

谢谢你，我又回到了以前的报错环节了😊

![image](https://github.com/xiaoleGun/KernelSU_Action/assets/111641284/386c62dd-2733-46e9-ab94-1d2beee3e0b4)

**Comment by univers629** [comment]
patch开启会报错，Apply KernelSU Patch关闭就能成功构建

**Comment by bdqllW** [comment]
> patch开启会报错，Apply KernelSU Patch关闭就能成功构建

你的内核源码已经修改过了吧？

**Comment by univers629** [comment]
> > patch开启会报错，Apply KernelSU Patch关闭就能成功构建
> 
> 你的内核源码已经修改过了吧？

应该不是的，因为上面图里报错的是未定义的变量
