### ISSUE TITLE
增加lkm for kernelsu的构建

### ISSUE THREAD

**Issue by smile349** [xiaoleGun/KernelSU_Action#150]
大部分内核源码无法编译出可开机的内核，但是可以编译出内核模块，并且内核模块的通用性很强，对于非gki设备，几乎每台设备的每个版本的系统都需要单独构建内核，lkm工作模式我的非gki设备使用安卓11的内核源码编译出的.ko内核模块能在安卓13的MIUI14上面正常使用，我的设备并没有可用的安卓13的内核源码，但是lkm可以让kernelsu在安卓13上面工作，我希望能增加对lkm的自动构建。

**Comment by xiaoleGun** [comment]
lkm是针对于gki设备的

**Comment by xiaoleGun** [comment]
> 事实上，lkm并不是gki专属，内核版本大于等于4.19的都可以构建lkm工作模式的kernelsu

是否有lkm在non-gki上工作的实例？

**Comment by smile349** [comment]
https://github.com/tanz3/kernel_xiaomi_sm8350-miui






上善若水
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月1日(周六) 下午5:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaoleGun/KernelSU_Action] 增加lkm for kernelsu的构建 (Issue #150)




  
事实上，lkm并不是gki专属，内核版本大于等于4.19的都可以构建lkm工作模式的kernelsu
  
是否有lkm在non-gki上工作的实例？
