### ISSUE TITLE
下载内核代码错误

### ISSUE THREAD

**Issue by sizxiwu** [xiaoleGun/KernelSU_Action#155]
![image](https://github.com/xiaoleGun/KernelSU_Action/assets/121373708/1747673b-4534-4e25-b21e-503642e57ac4)
KERNEL_SOURCE=https://github.com/crdroidandroid/android_kernel_motorola_sm7325
KERNEL_SOURCE_BRANCH=lineage-20

**Comment by xiaoleGun** [comment]
实测我没问题呢，不大清楚是哪方面的问题
