### ISSUE TITLE
build kernel最后不知道是哪出问题了，大佬能不能看看

### ISSUE THREAD

**Issue by p88oo** [xiaoleGun/KernelSU_Action#157]
换了几个编译工具最后总是出现几乎同样的问题
  
  MODPOST vmlinux.o
WARNING: EXPORT symbol "gsi_write_channel_scratch" [vmlinux] version generation failed, symbol will not be versioned.
ld.lld: error: relocation R_AARCH64_ABS32 cannot be used against symbol __crc_gsi_write_channel_scratch; recompile with -fPIC
>>> defined in built-in.a(drivers/platform/msm/gsi/gsi.o)
>>> referenced by gsi.c
>>>               drivers/platform/msm/gsi/gsi.o:(___kcrctab+gsi_write_channel_scratch+0x0) in archive built-in.a
make[1]: *** [/home/runner/work/LXC_KernelSU_Action/LXC_KernelSU_Action/kernel_workspace/android-kernel/Makefile:1177: vmlinux] Error 1
make[1]: Leaving directory '/home/runner/work/LXC_KernelSU_Action/LXC_KernelSU_Action/kernel_workspace/android-kernel/out'
make: *** [Makefile:146: sub-make] Error 2
Error: Process completed with exit code 2.

**Comment by xiaoleGun** [comment]
https://github.com/dev-sm8350/kernel_oneplus_sm8350/commit/c6d177f6ecfa6e8f33fdf919987b4440686b1bfe 参考这条commit
