### ISSUE TITLE
构建完了没有文件提示空

### ISSUE THREAD

**Issue by sudo0m** [xiaoleGun/KernelSU_Action#17]
![Snipaste_2023-03-13_18-45-29](https://user-images.githubusercontent.com/35640560/224679757-25ef99e4-a13d-46ef-adc8-8cb00250eda3.png)

地址![https://github.com/sudo0m/KernelSU_Action-kebab/actions/runs/4403631318/jobs/7712235487](https://github.com/sudo0m/KernelSU_Action-kebab/actions/runs/4403631318/jobs/7712235487)

这是我什么地方弄错了吗

**Comment by xiaoleGun** [comment]
https://github.com/sudo0m/KernelSU_Action-kebab/actions/runs/4403631318/jobs/7712235487#step:10:5274

改成Image

**Comment by sudo0m** [comment]
谢谢
