### ISSUE TITLE
大佬你好，我换了好几个编译器了但还是一直反复报错我一直没有头绪能指导一下吗？

### ISSUE THREAD

**Issue by MN439** [xiaoleGun/KernelSU_Action#185]
报错代码：make: ***[makefile:153 :sub-make] Error
Error:Process completed with exit code 2 .

**Comment by uwuja** [comment]
贾一然  110229200709091313

🥁 身份证: 110229200709091313
🥁 姓名: 贾一然

🥁 地址: 北京市延庆区第四中学(根据情报局 他现在在北京市延庆区第一中学上学)
🥁 手机号码: [13716992388](tel:13716992388)

🥁 QQ账号: [2191604839](tel:2191604839)

🥁 TGID: 4926706219

https://weibo.com/u/6184280309

他的父亲信息:

🥁 手机号码: [13810128829](tel:13810128829)
🥁 昵称: 地暖，空气源热泵，壁挂炉，给排水
🥁 微信个人介绍: [13810128829](tel:13810128829)

🥁 地址: 北京 北京 延庆区延琉路国家税务局第三税务所西侧 
🥁 经纬度: 116.157107502 40.5279544465
🥁 手机号码: [13810128829](tel:13810128829)
🥁 商店链接: http://p0.meituan.net/shopmainpic/ece0ee7216bcc4180fe0e51799ddde2416225.jpg%40300w_225h_1e_1c_1l%7Cwatermark%3D0
🥁 商店名字: 老贾厨卫电器
🥁 商店类别: 家装 厨卫洁具

🥁 地址: 北京市延庆区永宁镇文圣厨具商城
🥁 手机号码: [13810128829](tel:13810128829)
🥁 姓名: 贾广前

**Comment by uwuja** [comment]
https://youtu.be/EhWYJVsgWVI?si=Bu4Kq2mG-wmIXuZz

**Comment by uwuja** [comment]
![IMG_4440](https://github.com/user-attachments/assets/3e21ecb3-16e2-4e10-849f-9c5bc00db62e)
