### ISSUE TITLE
关于Workflow中的clang-aosp下载使用更新的链接

### ISSUE THREAD

**Issue by PianCat** [xiaoleGun/KernelSU_Action#23]
因为有一些内核需要使用clang-17进行编译才会有比较好或者比较稳定的产出，以及该目录下也包含了有旧版的clang，想问问是不是使用更新更快的分支会好点？
`https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-${{ env.CLANG_VERSION }}.tar.gz`
我所使用的是这个clang下载链接，https://github.com/PianCat/KernelSU_Action 这个是我fork下来的项目，经过测试可以编译产出稳定的KernelSU Kernel

**Comment by xiaoleGun** [comment]
https://github.com/xiaoleGun/KernelSU_Action/commit/0adabee5087b1a72ee3bc6164af91e3e9993c69b 已解决
