### ISSUE TITLE
编译内核时出错了大佬能帮忙看下吗

### ISSUE THREAD

**Issue by VMCoud** [xiaoleGun/KernelSU_Action#43]
*** Please run some configurator (e.g. "make oldconfig" or
*** "make menuconfig" or "make xconfig").
***
make[3]: *** [../scripts/kconfig/Makefile:38: silentoldconfig] Error 1
make[2]: *** [../Makefile:541: silentoldconfig] Error 2
make[1]: *** No rule to make target 'include/config/auto.conf', needed by 'include/config/kernel.release'.  Stop.
make: *** [Makefile:152: sub-make] Error 2
make[1]: Leaving directory '/home/runner/work/KernelSU_Action/KernelSU_Action/kernel_workspace/android-kernel/out'
Error: Process completed with exit code 2.

**Comment by xiaoleGun** [comment]
配置文件不对
