### ISSUE TITLE
const 错误

### ISSUE THREAD

**Issue by likkai** [xiaoleGun/KernelSU_Action#48]
内核被成功编译可是刷到手机上却无法使用 (触屏无反应，无法检测电池电量)，可是在 wsl 2 和 ubuntu 22.04.2 LTS 编译却没有问题。
[error.txt](https://github.com/xiaoleGun/KernelSU_Action/files/11768555/error.txt)

**Comment by xiaoleGun** [comment]
不提供内核方面支持，你这个可能是编译器或某些优化的问题
