### ISSUE TITLE
Redmi 10X 4G(merlin) Built error.

### ISSUE THREAD

**Issue by yuitoTDF** [xiaoleGun/KernelSU_Action#72]
My repository: github.com/yuitoTDF/KernelSU_Action (forked from this repository)

- config.env
```config
KERNEL_SOURCE=https://github.com/MiCode/Xiaomi_Kernel_OpenSource/
KERNEL_SOURCE_BRANCH=merlin-r-oss
KERNEL_CONFIG=defconfig
KERNEL_IMAGE_NAME=Image.gz
ARCH=arm64
EXTRA_CMDS:LD=ld.lld

# Clang
## Custom
USE_CUSTOM_CLANG=false
CUSTOM_CLANG_SOURCE=
CUSTOM_CLANG_BRANCH=

### if your set USE CUSTOM CLANG to false than DO NOT CHANGE CUSTOM CMDS
CUSTOM_CMDS:CLANG_TRIPLE=aarch64-linux-gnu-

## AOSP
CLANG_BRANCH=master-kernel-build-2022
CLANG_VERSION=r450784d

# GCC
ENABLE_GCC_ARM64=true
ENABLE_GCC_ARM32=true

# KernelSU flags
ENABLE_KERNELSU=true
KERNELSU_TAG=
KSU_EXPECTED_SIZE=
KSU_EXPECTED_HASH=

# Configuration
DISABLE-LTO=false
DISABLE_CC_WERROR=false
ADD_KPROBES_CONFIG=false
ADD_OVERLAYFS_CONFIG=false

# Ccache
ENABLE_CCACHE=true

# DTBO image
NEED_DTBO=false

# Build boot images
BUILD_BOOT_IMG=true
SOURCE_BOOT_IMAGE=https://bigota.d.miui.com/V13.0.1.0.SJOCNXM/merlin_images_V13.0.1.0.SJOCNXM_20220607.0000.00_12.0_cn_51efaee93c.tgz
```

- error report
```
/usr/bin/as: unrecognized option '-EL'
clang-14: error: assembler command failed with exit code 1 (use -v to see invocation)
make[3]: *** [../scripts/Makefile.build:357: scripts/mod/empty.o] Error 1
make[2]: *** [../scripts/Makefile.build:671: scripts/mod] Error 2
make[1]: *** [/home/runner/work/KernelSU_Action/KernelSU_Action/kernel_workspace/android-kernel/Makefile:580: scripts] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/runner/work/KernelSU_Action/KernelSU_Action/kernel_workspace/android-kernel/out'
make: *** [Makefile:146: sub-make] Error 2
Error: Process completed with exit code 2.
```

Goto Github Action on https://github.com/yuitoTDF/KernelSU_Action/actions/runs/5689348420/job/15420689618 to see more details.

或许是内核源码（github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/merlin-r-oss）的问题？我在Codespace也无法make内核。

I'm looking forward for your reply.

**Comment by yuitoTDF** [comment]
I edited the build-kernel.yml, and solve this problem:[#74 ](https://github.com/xiaoleGun/KernelSU_Action/pull/74)
Added:
```yaml
    - name: Install aarch64-linux-gnu
      run: |
        sudo apt-get install aarch64-linux-gnu
        sudo apt-get install gcc-aarch64-linux-gnu
        export PATH=/usr/aarch64-linux-gnu/bin/:$PATH:/usr/lib/gcc/x86_64-linux-gnu/9:/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrappe
```

**Comment by xiaoleGun** [comment]
https://github.com/kdrag0n/proton_zf6/commit/6e87fec9a3df5

https://github.com/kdrag0n/proton_zf6/commit/68acd6966ac98

**Comment by xyychenchen** [comment]
hello, I have this unrecognized 'EL' option issue, and I tried to use your solution but it shows :
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package aarch64-linux-gnu

**Comment by yuitoTDF** [comment]
> hello, I have this unrecognized 'EL' option issue, and I tried to use your solution but it shows :
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package aarch64-linux-gnu 

It's exactly the issue of 'as'. You can go and search solutions with prompt 'as -EF'. Hope it helps.
