### ISSUE TITLE
无法获取谷歌clang

### ISSUE THREAD

**Issue by MrNya907** [xiaoleGun/KernelSU_Action#76]
怎么修改都提示bad requset下载不了我想要的r450784d这个版本

**Comment by xiaoleGun** [comment]
检查clang branch

**Comment by CLT-MAX** [comment]
我也遇到了下载clang的问题，按照您的示例填写的，会出现400 bad requset
我也试着原封不动的运行了您的示例，在下载这个步骤必定出现问题

**Comment by CLT-MAX** [comment]
即便如此，我仍然试着用不同的branch及clang版本，但是除了您示例中使用的“master-kernel-build-2022”会出现400以外
改为如“master”:"r450784d"，“android12-release”:"r450784d"，“android10-release”:"r353983c",都无一例外的请求了“https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads//clang-.tar.gz”这个地址并且返回了404。

**Comment by CLT-MAX** [comment]
不好意思，我上面的报告失误
经过查询workflow，我发现是“准备配置”部分出现问题
全部的环境变量都没有设置，不确定是什么导致的

**Comment by kissunyeason** [comment]
> 怎么修改都提示bad requset下载不了我想要的r450784d这个版本

把master改成main，我也是这样的问题

**Comment by QKIvan** [comment]
> lang branch

应该是给移除了。
参考https://github.com/QKIvan/KernelSU_Action/actions/runs/5901786445/job/16008580755
你现在用master/main分支都是拉不到的
参考这个提交，https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/9e42e3d60007186675c1117ff6bd6ac91e8b7da8
r450784d在master-kernel-build-2022这个分支是存在的。

**Comment by QKIvan** [comment]
> > 怎么修改都提示bad requset下载不了我想要的r450784d这个版本
> 
> 把master改成main，我也是这样的问题

应该是给移除了。
参考https://github.com/QKIvan/KernelSU_Action/actions/runs/5901786445/job/16008580755
你现在用master/main分支都是拉不到的
参考这个提交，https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/9e42e3d60007186675c1117ff6bd6ac91e8b7da8
r450784d在master-kernel-build-2022这个分支是存在的。

**Comment by QKIvan** [comment]
> > 怎么修改都提示bad requset下载不了我想要的r450784d这个版本
> 
> 把master改成main，我也是这样的问题

r450784d已经给Google Remove了，包括master/master-kernel-build-2022和你说的main，至于master-kernel-build-2021，本来也没有这个版本
参考https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/4d52068718fb7940b103cc49506f77e5d22f25df（master/main）
https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/9f759dee5cdc5f85d076c642a192f6a9232f7058（这个是master-kernel-build-2022分支，在7.26被移除）
看来有必要把默认的版本换成新一点的clang了。
