### ISSUE TITLE
Error kernelsu action

### ISSUE THREAD

**Issue by QPLAYid** [xiaoleGun/KernelSU_Action#8]
![Screenshot_2023-01-29-14-46-49-857_com brave browser](https://user-images.githubusercontent.com/102419809/215308276-e1d6fc71-f035-4f8d-9a89-9169771ceb92.jpg)

**Comment by xiaoleGun** [comment]
仓库的issues仅供解决本身问题，你这个属于内核源码的问题

**Comment by QPLAYid** [comment]
So cant used kernelsu action ?
