### ISSUE TITLE
Bulid kernel出错

### ISSUE THREAD

**Issue by Athena-CN** [xiaoleGun/KernelSU_Action#80]
make[1]: Leaving directory '/home/runner/work/KernelSU_Action/KernelSU_Action/kernel_workspace/android-kernel/out'
make: *** [Makefile:146: sub-make] Error 2
Error: Process completed with exit code 2. 作者你好 请问这个问题怎么解决啊

**Comment by Rayspp** [comment]
me too

**Comment by ZYD20200827** [comment]
换一个编译器 吧

**Comment by xiaoleGun** [comment]
内核编译问题不属于本项目bug
