### ISSUE TITLE
BUILD_BOOT_IMG=false是不是可以SOURCE_BOOT_IMAGE=留空不设值?

### ISSUE THREAD

**Issue by ottoskyer** [xiaoleGun/KernelSU_Action#93]
只要BUILD_BOOT_IMG=false,
SOURCE_BOOT_IMAGE设值不设值都没影响,是这样吗?

这两项不影响最终内核使用,是这样吗?

这两项的关键作用是什么?
![Screenshot_2023-09-18-18-05-06-88_9c7ad408470e52983cc8816adf9ff347](https://github.com/xiaoleGun/KernelSU_Action/assets/40727785/5bf7069c-67e7-42e6-98d0-a63d72d036e7)

**Comment by QKIvan** [comment]
https://github.com/xiaoleGun/KernelSU_Action/blob/main/README.md#source-boot-image
README这边写的还是挺清楚的，这个选项只是用来构建boot.img的，并不会影响内核的使用。
以及在BUILD_BOOT_IMG=false的情况下，SOURCE_BOOT_IMAGE你写啥都不会影响。（因为不会构建boot.img）
项目默认会将构建出来的Image.gz-dtb和AnyKernel3打包，直接通过Recovery刷入即可。
